branch-defaults:
  default:
    environment: Tuanla122-last-env-1
environment-defaults:
  Tuanla122-last-env-1:
    branch: null
    repository: null
global:
  application_name: tuanla122-last
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application

deploy:
  artifact: www/Archive.zip
